In [3]:
import numpy as np
import pandas as pd

# Display options
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 100)

In [5]:
df = pd.read_csv("amazon_products_merged.csv")

In [9]:
df

,asin,title,amazon_category,category_id,imgUrl,productURL,stars,reviews,price,listPrice,isBestSeller,boughtInLastMonth
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black, Checked-Large 29-Inch",Suitcases,104,https://m.media-amazon.com/images/I/815dLQKYIYL._AC_UL320_.jpg,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,False,2000
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcase Double Wheels TSA Lock Blue,Suitcases,104,https://m.media-amazon.com/images/I/81bQlm7vf6L._AC_UL320_.jpg,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,False,1000
2,B07XSCCZYG,"Platinum Elite Softside Expandable Checked Luggage, 8 Wheel Spinner Suitcase, TSA Lock, Men and ...",Suitcases,104,https://m.media-amazon.com/images/I/71EA35zvJBL._AC_UL320_.jpg,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,False,300
3,B08MVFKGJM,"Freeform Hardside Expandable with Double Spinner Wheels, Navy, 2-Piece Set (21/28)",Suitcases,104,https://m.media-amazon.com/images/I/91k6NYLQyIL._AC_UL320_.jpg,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,False,400
4,B01DJLKZBA,"Winfield 2 Hardside Expandable Luggage with Spinner Wheels, Checked-Large 28-Inch, Deep Blue",Suitcases,104,https://m.media-amazon.com/images/I/61NJoaZcP9L._AC_UL320_.jpg,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,False,400
...,...,...,...,...,...,...,...,...,...,...,...,...
1426332,B00R3LIKCO,American Flag Patriotic USA Classic 5 Panel Mesh Snap Back Trucker Hat,Men's Accessories,112,https://m.media-amazon.com/images/I/71PDJFz6AAL._AC_UL320_.jpg,https://www.amazon.com/dp/B00R3LIKCO,4.2,0,14.95,0.00,False,0
1426333,B098BQ7ZQ3,Men's Baseball Cap - H2O-DRI Line Up Curved Brim Fitted Hat,Men's Accessories,112,https://m.media-amazon.com/images/I/812Tycexs4L._AC_UL320_.jpg,https://www.amazon.com/dp/B098BQ7ZQ3,4.4,0,33.99,0.00,False,0
1426334,B07X1MVNT1,"[4 Pack] Adjustable Eyeglasses and Sunglasses Holder Strap Cord for Sports, Anti-slippery Eyegla...",Men's Accessories,112,https://m.media-amazon.com/images/I/61vvYW1S9JL._AC_UL320_.jpg,https://www.amazon.com/dp/B07X1MVNT1,3.6,0,8.54,0.00,False,0
1426335,B08XLBG8V9,Ax2002 Aviator Sunglasses,Men's Accessories,112,https://m.media-amazon.com/images/I/51+yjD4F1xL._AC_UL320_.jpg,https://www.amazon.com/dp/B08XLBG8V9,4.5,0,54.36,57.39,False,0
1426336,B07GH67QC8,in Hoc Signo Vinces Knights Templar Masonic Embroidered Black Adjustable Baseball Cap,Men's Accessories,112,https://m.media-amazon.com/images/I/91Kt2KQf0EL._AC_UL320_.jpg,https://www.amazon.com/dp/B07GH67QC8,4.9,0,18.79,0.00,False,0

In [12]:
df.head()
df.info()
df.shape
df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426337 entries, 0 to 1426336
Data columns (total 12 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   asin               1426337 non-null  object
 1   title              1426336 non-null  object
 2   amazon_category    1426337 non-null  object
 3   category_id        1426337 non-null  int64
 4   imgUrl             1426337 non-null  object
 5   productURL         1426337 non-null  object
 6   stars              1426337 non-null  float64
 7   reviews            1426337 non-null  int64
 8   price              1426337 non-null  float64
 9   listPrice          1426337 non-null  float64
 10  isBestSeller       1426337 non-null  bool
 11  boughtInLastMonth  1426337 non-null  int64
dtypes: bool(1), float64(3), int64(3), object(5)
memory usage: 121.1+ MB

,asin,title,amazon_category,category_id,imgUrl,productURL,stars,reviews,price,listPrice,isBestSeller,boughtInLastMonth
count,1426337,1426336,1426337,1.426337e+06,1426337,1426337,1.426337e+06,1.426337e+06,1.426337e+06,1.426337e+06,1426337,1.426337e+06
unique,1426337,1385430,248,NaN,1372162,1426337,NaN,NaN,NaN,NaN,2,NaN
top,B014TMV5YE,Men's Sneaker,Girls' Clothing,NaN,https://m.media-amazon.com/images/I/01RmK+J4pJL._AC_UL320_.gif,https://www.amazon.com/dp/B014TMV5YE,NaN,NaN,NaN,NaN,False,NaN
freq,1,89,28619,NaN,1130,1,NaN,NaN,NaN,NaN,1417817,NaN
mean,NaN,NaN,NaN,1.237409e+02,NaN,NaN,3.999512e+00,1.807508e+02,4.337540e+01,1.244916e+01,NaN,1.419823e+02
std,NaN,NaN,NaN,7.311273e+01,NaN,NaN,1.344292e+00,1.761453e+03,1.302893e+02,4.611198e+01,NaN,8.362720e+02
min,NaN,NaN,NaN,1.000000e+00,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN,0.000000e+00
25%,NaN,NaN,NaN,6.500000e+01,NaN,NaN,4.100000e+00,0.000000e+00,1.199000e+01,0.000000e+00,NaN,0.000000e+00
50%,NaN,NaN,NaN,1.200000e+02,NaN,NaN,4.400000e+00,0.000000e+00,1.995000e+01,0.000000e+00,NaN,0.000000e+00
75%,NaN,NaN,NaN,1.760000e+02,NaN,NaN,4.600000e+00,0.000000e+00,3.599000e+01,0.000000e+00,NaN,5.000000e+01
max,NaN,NaN,NaN,2.700000e+02,NaN,NaN,5.000000e+00,3.465630e+05,1.973181e+04,9.999900e+02,NaN,1.000000e+05

In [14]:
df.columns

Index(['asin', 'title', 'amazon_category', 'category_id', 'imgUrl',
       'productURL', 'stars', 'reviews', 'price', 'listPrice', 'isBestSeller',
       'boughtInLastMonth'],
      dtype='object')

In [16]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [18]:
df.columns

Index(['asin', 'title', 'amazon_category', 'category_id', 'imgurl',
       'producturl', 'stars', 'reviews', 'price', 'listprice', 'isbestseller',
       'boughtinlastmonth'],
      dtype='object')

In [21]:
df.isnull().sum()
missing = (
    df.isnull()
      .sum()
      .to_frame("Missing Values")
)

missing["Percentage"] = (
    missing["Missing Values"] / len(df) * 100
)

missing.sort_values("Percentage", ascending=False)

                   Missing Values  Percentage
title                           1     0.00007
asin                            0     0.00000
amazon_category                 0     0.00000
category_id                     0     0.00000
imgurl                          0     0.00000
producturl                      0     0.00000
stars                           0     0.00000
reviews                         0     0.00000
price                           0     0.00000
listprice                       0     0.00000
isbestseller                    0     0.00000
boughtinlastmonth               0     0.00000

In [34]:
# Removing duplicate products
df.duplicated().sum()

np.int64(0)

In [35]:
# Checking ASIN duplicates
df["asin"].duplicated().sum()
# If exists
df = df.drop_duplicates(subset="asin")

In [25]:
#Clean price column
df["price"].head()

0    139.99
1    169.99
2    365.49
3    291.59
4    174.99
Name: price, dtype: float64

In [27]:
#Converting data types if any 
df.dtypes

asin                  object
title                 object
amazon_category       object
category_id            int64
imgurl                object
producturl            object
stars                float64
reviews                int64
price                float64
listprice            float64
isbestseller            bool
boughtinlastmonth      int64
dtype: object

In [29]:
#Validate values
df[df["price"] < 0]

Empty DataFrame
Columns: [asin, title, amazon_category, category_id, imgurl, producturl, stars, reviews, price, listprice, isbestseller, boughtinlastmonth]
Index: []

In [43]:
# Removing unecessary columns which do not support the business analysis 
print(df.columns.tolist())

['asin', 'amazon_category', 'category_id', 'stars', 'reviews', 'price', 'listprice', 'isbestseller', 'boughtinlastmonth']

In [45]:
# Verify
df.head()

,asin,amazon_category,category_id,stars,reviews,price,listprice,isbestseller,boughtinlastmonth
0,B014TMV5YE,Suitcases,104,4.5,0,139.99,0.00,False,2000
1,B07GDLCQXV,Suitcases,104,4.5,0,169.99,209.99,False,1000
2,B07XSCCZYG,Suitcases,104,4.6,0,365.49,429.99,False,300
3,B08MVFKGJM,Suitcases,104,4.6,0,291.59,354.37,False,400
4,B01DJLKZBA,Suitcases,104,4.5,0,174.99,309.99,False,400

In [46]:
df.to_csv(
    "amazon_products_clean.csv",
    index=False
)